workflows:
  expo-app:
    name: Build Expo Android App
    instance_type: linux_x2
    environment:
      node: 18.17.0
      vars:
        EXPO_TOKEN: Encrypted_your_token_here
    scripts:
      - npm install -g expo-cli
      - npm ci
      - expo login --token $EXPO_TOKEN
      - expo install
      - expo build:android --non-interactive
    artifacts:
      - /build/*.apk
      - /build/**/*.apk
