workflows:
  expo-ios:
    name: Build MagdaRecords iOS .ipa
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        EXPO_PROJECT_ROOT: .
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install EAS CLI
        script: |
          npm install -g eas-cli

      - name: Build iOS .ipa using EAS
        script: |
          eas build -p ios --profile preview --non-interactive

    artifacts:
      - build/**/*.ipa

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
