workflows:
  expo-app:
    name: Build MagdaRecords Android AAB
    instance_type: mac_mini_m1  # Change to linux_x2 if you're only targeting Android and want a free tier option
    max_build_duration: 60
    environment:
      vars:
        EXPO_PROJECT_ROOT: .
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install EAS CLI
        script: |
          npm install -g eas-cli

      - name: Build Android .aab using EAS
        script: |
          eas build -p android --profile preview --non-interactive

    artifacts:
      - build/**/*.aab
      - build/**/*.apk

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
