workflows:
  expo-app:
    name: Build MagdaRecords Android AAB
    instance_type: mac_mini_m1  # Or use 'linux_x2' for Android only, cheaper
    max_build_duration: 60
    environment:
      vars:
        EXPO_PROJECT_ROOT: .
      node: 18
      expo: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install Expo CLI
        script: |
          npm install -g expo-cli

      - name: Create .aab file
        script: |
          eas build -p android --profile preview --non-interactive

    artifacts:
      - build/**/*.aab
      - build/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
